services:
  - type: web
    name: evenvo-demo
    env: node
    repo: https://github.com/EvSol28/Evenvo-Demo
    branch: main
    buildCommand: apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev pkg-config python3 && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0