services:
  - type: web
    name: evenvo-demo-premium
    env: node
    repo: https://github.com/EvSol28/Evenvo-Demo-Premium
    branch: main
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node Evenvo-Demo-Premieum/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      # Les autres variables Firebase doivent être configurées via l'interface Render
      # pour des raisons de sécurité. Voir RENDER_SETUP.md